name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # This uses the system's Gradle instead of your missing wrapper
      - name: Build with Gradle
        run: |
          cd app
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeoExplorer-APK
          path: app/build/outputs/apk/debug/app-debug.apk
