name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # This action sets up Gradle properly
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Now use ./gradlew with the correct path
      - name: Build with Gradle
        run: |
          cd app
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeoExplorer-APK
          path: app/build/outputs/apk/debug/app-debug.apk
