name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Use the NEW setup-gradle action (non-deprecated)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Build using Gradle directly (no wrapper needed)
      - name: Build with Gradle
        run: |
          cd app
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeoExplorer-APK
          path: app/build/outputs/apk/debug/app-debug.apk
